# Generated by Django 4.2.17 on 2025-01-04 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skinapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertable',
            old_name='questions',
            new_name='previous_history',
        ),
    ]
