# Generated by Django 4.2.17 on 2025-01-13 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skinapp', '0002_rename_questions_usertable_previous_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='username',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='username',
        ),
        migrations.AddField(
            model_name='complaints',
            name='USER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skinapp.usertable'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='USER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skinapp.usertable'),
        ),
    ]
