# Generated by Django 4.2.17 on 2025-01-13 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skinapp', '0003_remove_complaints_username_remove_feedback_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='loginid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skinapp.logintable'),
        ),
    ]
