# Generated by Django 4.2.17 on 2025-01-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skinapp', '0004_alter_usertable_loginid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='regster',
        ),
    ]
